name: CI/CD to Haenu Cluster - Development

on:
  push:
    branches: [dev]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo API_ADDRESS=\"${{ secrets.API_ADDRESS }}\" >>  .env
          echo API_PORT=\"${{ secrets.API_PORT }}\" >> .env
          echo ROOT_DOMAIN=\"${{ secrets.ROOT_DOMAIN }}\" >> .env
          echo LOGIN_REDIRECT_ADDRESS=\"${{ secrets.LOGIN_REDIRECT_ADDRESS }}\" >> .env
          echo MYSQL_HOST=\"${{ secrets.MYSQL_HOST }}\" >> .env
          echo MYSQL_PORT=\"${{ secrets.MYSQL_PORT }}\" >> .env
          echo MYSQL_USERNAME=\"${{ secrets.MYSQL_USERNAME }}\" >> .env
          echo MYSQL_PASSWORD=\"${{ secrets.MYSQL_PASSWORD }}\" >> .env
          echo MYSQL_DATABASE=\"${{ secrets.MYSQL_DATABASE }}\" >> .env
          echo REDIS_HOST=\"${{ secrets.REDIS_HOST }}\" >> .env
          echo REDIS_PORT=\"${{ secrets.REDIS_PORT }}\" >> .env
          echo REDIS_PASSWORD=\"${{ secrets.REDIS_PASSWORD }}\" >> .env
          echo JWT_SECRET=\"${{ secrets.JWT_SECRET }}\" >> .env
          echo TWITCH_CLIENT_ID=\"${{ secrets.TWITCH_CLIENT_ID }}\" >> .env
          echo TWITCH_CLIENT_SECRET=\"${{ secrets.TWITCH_CLIENT_SECRET }}\" >> .env
          echo GOOGLE_CLIENT_ID=\"${{ secrets.GOOGLE_CLIENT_ID }}\" >> .env
          echo GOOGLE_CLIENT_SECRET=\"${{ secrets.GOOGLE_CLIENT_SECRET }}\" >> .env
          echo CLOUDFLARE_ACCOUNT_ID=\"${{ secrets.CLOUDFLARE_ACCOUNT_ID }}\" >> .env
          echo CLOUDFLARE_IMAGES_TOKEN=\"${{ secrets.CLOUDFLARE_IMAGES_TOKEN }}\" >> .env
          echo CLOUDFLARE_IMAGES_CDN_ADDRESS=\"${{ secrets.CLOUDFLARE_IMAGES_CDN_ADDRESS }}\" >> .env
          echo CLOUDFLARE_R2_ACCESS_KEY=\"${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}\" >> .env
          echo CLOUDFLARE_R2_SECRET_ACCESS_KEY=\"${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}\" >> .env
          echo CLOUDFLARE_R2_CDN_ADDRESS=\"${{ secrets.CLOUDFLARE_R2_CDN_ADDRESS }}\" >> .env
          echo NODE_ENV=\"${{ secrets.NODE_ENV }}\" >> .env
          # Add other variables as needed

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyeonwoo5342/dev-musicbook-be:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          repository: dokdo2013/haenu-cluster
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update deployment tag in GitOps repo
        run: |
          APP_NAME="dev-musicbook-be"
          cd gitops/apps/${APP_NAME}
          sed -i "s|image: hyeonwoo5342/${APP_NAME}:.*|image: hyeonwoo5342/${APP_NAME}:${{ github.run_number }}|g" deployment.yaml
          git config user.name "dokdo2013"
          git config user.email "hyeonwoo5342@gmail.com"
          git add .
          git commit -m "feat(${APP_NAME}): Build and deploy new commit ${{ github.run_number }}"
          git push
